# This file was automatically generated by Gaffer.
# Do not edit this file - it will be overwritten.

import Gaffer
import GafferUI

bookmarks = GafferUI.Bookmarks.acquire( application, Gaffer.FileSystemPath, 'procedurals' )
bookmarks.addRecent( 'D:/' )
bookmarks = GafferUI.Bookmarks.acquire( application, Gaffer.FileSystemPath, 'script' )
bookmarks.addRecent( 'D:/dropbox/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes/logo_v001.gfr' )
bookmarks.addRecent( 'E:/work2/gaffer/queen_v001.gfr' )
bookmarks.addRecent( 'E:/work2/gaffer' )
bookmarks.addRecent( 'D:/dropbox/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes' )
bookmarks.addRecent( 'C:/Users/herib/Downloads' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes' )
bookmarks = GafferUI.Bookmarks.acquire( application, Gaffer.FileSystemPath, 'image' )
bookmarks.addRecent( 'D:/renderings/streams' )
bookmarks.addRecent( 'D:/renderings/temp2' )
bookmarks.addRecent( 'D:/renderings/streams/untitled.####.exr' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/hdri/Tokyo_BigSight_3k.tx' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/hdri' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/hdri/rooftop_day_2k.hdr.tex' )
bookmarks = GafferUI.Bookmarks.acquire( application, Gaffer.FileSystemPath, 'sceneCache' )
bookmarks.add( 'D:/dropbox/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/houdini/geo/streams2.abc', 'C:/Users/herib/gaffer-0.55.2.1-windows/bin', persistent=True )
bookmarks.addRecent( 'E:/work2/gaffer/objects/sphere.abc' )
bookmarks.addRecent( 'D:/dropbox/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/houdini/geo/hexagon3.abc' )
bookmarks.addRecent( 'D:/dropbox/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/houdini/geo' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/houdini/geo/surface_points.abc' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/houdini/geo' )
bookmarks.addRecent( '/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/houdini/USD' )
