# This file was automatically generated by Gaffer.
# Do not edit this file - it will be overwritten.

import Gaffer
import IECore
import imath

Gaffer.Metadata.registerValue( application.root()["preferences"], "serialiser:milestoneVersion", 0, persistent=False )
Gaffer.Metadata.registerValue( application.root()["preferences"], "serialiser:majorVersion", 55, persistent=False )
Gaffer.Metadata.registerValue( application.root()["preferences"], "serialiser:minorVersion", 1, persistent=False )
Gaffer.Metadata.registerValue( application.root()["preferences"], "serialiser:patchVersion", 0, persistent=False )

__children = {}



del __children


