# This file was automatically generated by Gaffer.
# Do not edit this file - it will be overwritten.

import GafferUI
GafferUI.FileMenu.addRecentFile( application, "D:/dropbox/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes/logo_v015.gfr" )
GafferUI.FileMenu.addRecentFile( application, "E:/work2/gaffer/noise_v001.gfr" )
GafferUI.FileMenu.addRecentFile( application, "C:/Users/herib/Downloads/outputs.gfr" )
GafferUI.FileMenu.addRecentFile( application, "/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes/logo_v014.gfr" )
GafferUI.FileMenu.addRecentFile( application, "/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes/logo_v015.gfr" )
GafferUI.FileMenu.addRecentFile( application, "/home/heri/MiniEngine Dropbox/data/jobs/ULTM/sequences/A/shots/001/gaffer/scenes/logo_v016.gfr" )
